### PR TITLE
Update to KDE KF6

### PR DESCRIPTION
**Pull request by travier**

### CODE REVIEW

**Comment by espidev** [comment]
bot, build org.kde.kclock

**Comment by travier** [comment]
It's going to fail until we get the KF6 build which is still in progress. I'm posting the changes here for review and I'll retrigger a build once it's ready (likely tomorrow)

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
Looks like the appdata is incorrect:

```
$ flatpak list --user | grep kclock
KDE Community   org.kde.kclock  24.02.0 test    kclock-origin
```

**Comment by espidev** [comment]
What's wrong with the appdata?

**Comment by travier** [comment]
I don't know exactly but Flatpak shows "KDE Community" for the name instead of "KClock". Likely because on older (pre AppStream 1.0) systems, the `<developer>` tag is not supported and may confuse Flatpak. Not sure yet.

**Comment by espidev** [comment]
I think we should go ahead with this for now

**Pull request merged**
